## Importing NumPy array

In [1]:
import numpy as np

### 1-D array

In [2]:
array1 = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
array1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [3]:
print(array1)

[ 2  4  6  8 10 12 14 16 18 20]


In [4]:
type(array1) #type() returns the array type

numpy.ndarray

In [5]:
array1.shape  #shape will return the shape of the numpy array

(10,)

### 2-D array

In [7]:
array2 = np.array([ [1, 3, 5], [2, 4, 6] ])
array2

array([[1, 3, 5],
       [2, 4, 6]])

In [8]:
print(array2)

[[1 3 5]
 [2 4 6]]


In [9]:
array2.ndim #ndim returns the dimention of the numpy array

2

In [10]:
array1.ndim

1

In [12]:
array2.size #return the size(element number) of the array

6

In [13]:
array3 = np.array([3, 6, 9], dtype='int')
array3

array([3, 6, 9])

In [14]:
array4 = np.array([3, 6, 9], dtype='float')
array4

array([3., 6., 9.])

In [17]:
array5 = np.array([3, 6, 9], dtype='double')
array5

array([3., 6., 9.])



### zeros() method

In [18]:
zeros = np.zeros((3, 3))  #By defalult data type will float
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
zeros = np.zeros((4, 4), dtype='int')
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])



### ones() method

In [20]:
ones = np.ones((3, 3)) #by default data type is float
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
ones = np.ones((4, 4), dtype='int')
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])



### full() method

In [22]:
full = np.full((2,3), 5)
full

array([[5, 5, 5],
       [5, 5, 5]])

In [23]:
print(full)

[[5 5 5]
 [5 5 5]]




### indentify() method

In [27]:
identity = np.identity(5) #by fault data type is float
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
identity = np.identity(5, dtype='int') #by fault data type is float
identity

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])




### eye() method

In [29]:
eye1 = np.eye(3, 3)
eye1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
eye1 = np.eye(3, 3, 1)
eye1

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [31]:
eye1 = np.eye(3, 3, -1)
eye1

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])




### arange()


In [32]:
arange = np.arange(1, 20, 4)
arange

array([ 1,  5,  9, 13, 17])



### linspace() method

In [35]:
linspace = np.linspace(1, 5, 10) #(start, stop, how_many_value_I_want)
linspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])



### empty() method

In [36]:
empty = np.empty((1, 5), dtype='int')
empty

array([[1653589744,        427,          0,          0,     131074]])

In [ ]:
for i in range(5):
    empty(:)